version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB: stock_api
    depends_on:
      - mongo

  mongo:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
